services:
  - type: web
    name: barcode-scanner-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # Updated to match your app.py
    envVars:
      - fromGroup: barcode-env  # This should match the name of your env group in Render

  - type: worker
    name: barcode-scanner-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - fromGroup: barcode-env
