services:
  - type: web
    name: barcode-scanner
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"  # Install dependencies
    startCommand: "flask run --host 0.0.0.0"  # Start the Flask app

  - type: worker
    name: barcode-scanner-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"  # Install dependencies for worker
    startCommand: "python worker.py"  # Start the worker process (scheduler)
